version: 0.2

phases:
  install:
    commands:
       - echo "Installing AWS CDK."
       - npm install -g aws-cdk 
       - cd cdk/
       - python -m pip install -r requirements.txt
  build:
    commands:
       - echo "Deploying CDK stack for $ENV environemnt" 
       - cdk deploy --require-approval never --method=direct